rust_library(
    name = "vfdecrypt",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "third-party//:thiserror",
        "third-party//:aes",
        "third-party//:hmac",
        "third-party//:sha1",
        "third-party//:pbkdf2",
        "third-party//:des",
        "third-party//:cbc",
        "third-party//:cipher",
        "third-party//:rayon",
    ],
    visibility = ["PUBLIC"],
)
