load(":rules.bzl", "qemu_run")

qemu_run(
    name = "run_qemu",
    disk = "//:disk.img",
    kernel = "//src/kernel:kernel",
)

alias(
    name = "setup",
    actual = "//src/tools/gravity-setup:gravity-setup",
)
