rust_binary(
    name = "make-disk",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    edition = "2024",
    deps = [
        "third-party//:clap",
        "third-party//:tar",
        "third-party//:thiserror",
        "//src/lib/apple-dmg:apple-dmg",
        "//src/lib/hfsplus:hfsplus",
    ],
    visibility = ["PUBLIC"],
)
