rust_library(
    name = "hfsplus",
    srcs = glob(["*.rs"]),
    crate_root = "lib.rs",
    edition = "2024",
    deps = [
        "third-party//:bitflags",
        "third-party//:unicode-normalization",
        "third-party//:hashbrown",
        "third-party//:binrw",
        "third-party//:spin",
        "third-party//:zlib-rs",
    ],
    visibility = ["PUBLIC"],
)
